### ISSUE TITLE
Repeated calls to status() result in error

### ISSUE THREAD

**Issue by dvdsk** [jsvana/async-minecraft-ping#11]
I am using this crate (thanks :+1: ), to detect if a minecraft host went down. I use an async function which waits till a minecraft server is not longer reachable:

```rust
async fn unreachable(addr: SocketAddr) {
    use async_minecraft_ping::ConnectionConfig;
    async fn inner(addr: SocketAddr) -> Result<(), ()> {
        let mut conn = ConnectionConfig::build(addr.ip().to_string())
            .with_port(addr.port())
            .connect()
            .await
            .map_err(|_| ())?;
        loop {
            sleep(Duration::from_secs( 20)).await;
            conn.status().await.map_err(|_| ())?;
        }
    }
    let _ignore_res = inner(addr).await;
}
```

This variant of the function returns even though the server is up during the second iteration of the `loop`.

If I reconnect in each iteration of the loop everything works fine (this is fine for my use-case). Is `status()` only working once for a connection intended behavior or did I misunderstand the docs?

Again thanks for your work here, its very useful :+1:

**Comment by jsvana** [comment]
I'll take a look at this soon here. I'm not really familiar overall with the protocol and just got this up and running enough to get a JSON status response :(

Looking at https://wiki.vg/Server_List_Ping#Response (we first send a Handshake and then a Request when calling `status()`) it seems like we can only get the status once. Then we're meant to send Pings to the server. At one point I tried to get Pings working but stopped for some reason. It seems like having a repeatable `ping()` call would suit your needs here. What do you think?

**Comment by jsvana** [comment]
ServerListPing's pretty disappointing here. The server closes the connection after a single ping method. [This PR](https://github.com/jsvana/async-minecraft-ping/pull/12) makes it so that repeated calls are compiler errors, but that doesn't really help you. Unfortunately I think the best you can do is recreate the client each time :(

**Comment by dvdsk** [comment]
Hey thanks! recreating the client is no problem for me and thanks to that PR you made no one else will run into this :)
