### ISSUE TITLE
Use a std::Error based error crate like thiserror

### ISSUE THREAD

**Issue by 0xpr03** [jsvana/async-minecraft-ping#7]
I would recommend to use an library-level error-crate, something like [thiserror](https://github.com/dtolnay/thiserror) that works with any of the existing "Application" error systems. The upside is that users can also use something like [stable-eyre](https://crates.io/crates/stable-eyre) (which gives you backtraces on stable, works like anyhow) and other such systems.

Currently you [can't mix](https://github.com/yaahc/eyre/issues/31#issuecomment-656729031) them without additional overhead due to
```
error[E0277]: the trait bound `anyhow::Error: std::error::Error` is not satisfied
  --> src\main.rs:94:39
   |
94 |     let status = ping_c.status().await?;
   |                                       ^ the trait `std::error::Error` is not implemented 
for `anyhow::Error`
   |
   = note: required because of the requirements on the impl of `From<anyhow::Error>` for `ErrReport`
   = note: required by `from`
```

Another upside is that you don't allocate by default. (Which a user will probably box again inside their own anyhow-ish crate.)

If you're interested I can make a PR for that.

**Comment by jsvana** [comment]
I fully support moving to thiserror. You're right that anyhow makes usage super awkward. Sorry about that! Happy to review a PR for it, otherwise I'll see if I can get around to it this week.

**Comment by jsvana** [comment]
Sorry this took so long. I appreciate the PR you made and I know I dragged my feet on it. Since I made some other changes to the library I opted to make the change myself so things should be good to go now. Let me know if there are still issues!

**Comment by 0xpr03** [comment]
Ah no problem, I also didn't move forward much with those problem, so no worries ;) Glad to see you found a solution.
