### ISSUE TITLE
When given an invalid address/port, StatusConnection::status doesn't return

### ISSUE THREAD

**Issue by Hpmason** [jsvana/async-minecraft-ping#9]
For some unused ports/addresses, StatusConnection does not return, as it doesn't receive a response from the endpoint. Particularly this line in `StatusConnection`:
https://github.com/jsvana/async-minecraft-ping/blob/c2da0ec7774e458395ae779e999485bbe90e2f66/src/server.rs#L180-L184

Seems to get stuck on this read operation, which never returns
https://github.com/jsvana/async-minecraft-ping/blob/c2da0ec7774e458395ae779e999485bbe90e2f66/src/protocol.rs#L87

I don't know much about the TCP connection, but maybe setting a TTL will cause it to return with an error, that way it doesn't hang forever? This would also reduce time for connections that aren't minecraft server end points. 

For example (this is and example of something that hangs) using the following arguments: 
Address: `142.44.136.209` Port: `25566`

**Comment by scd31** [comment]
A quick fix is to wrap the future in a timeout: https://docs.rs/tokio/1.12.0/tokio/time/fn.timeout.html

This can be done without forking async-minecraft.ping.

**Comment by jsvana** [comment]
Sorry about the huge delay here. Hopefully this PR addresses the issue. @scd31 thanks for the suggestion. Made this super easy!
